version: '2'
services:
  nginx:
    container_name: mks-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
        UID: $UID
        GUID: $GUID
    links:
      - php
    ports:
      - $PORT:80
      - $HTTPS_PORT:443
    volumes_from:
      - php
    volumes:
      - "./shared/logs/nginx:/var/log/nginx"
    networks:
      default:
        aliases:
          - $NGINX_ALIAS
    restart: always
  php:
    container_name: mks-app
    image: ghcr.io/nochlezhka/mks:latest
    links:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: $MYSQL_DATABASE
      DB_USER: $MYSQL_USER
      DB_PASSWORD: $MYSQL_PASSWORD
      ORG_NAME_SHORT: $ORG_NAME_SHORT
      ORG_NAME: $ORG_NAME
      ORG_DESCRIPTION: $ORG_DESCRIPTION
      ORG_DESCRIPTION_SHORT: $ORG_DESCRIPTION_SHORT
      ORG_CITY: $ORG_CITY
      ORG_CONTACTS_FULL: $ORG_CONTACTS_FULL
      DISPENSARY_NAME: $DISPENSARY_NAME
      DISPENSARY_ADDRESS: $DISPENSARY_ADDRESS
      DISPENSARY_PHONE: $DISPENSARY_PHONE
      EMPLOYMENT_NAME: $EMPLOYMENT_NAME
      EMPLOYMENT_ADDRESS: $EMPLOYMENT_ADDRESS
      EMPLOYMENT_INSPECTION: $EMPLOYMENT_INSPECTION
      SANITATION_NAME: $SANITATION_NAME
      SANITATION_ADDRESS: $SANITATION_ADDRESS
      SANITATION_TIME: $SANITATION_TIME
    restart: always
  db:
    container_name: mks-db
    image: mysql:8.0.29
    expose:
        - "3306"
    ports:
        - 127.0.0.1:$MYSQL_PORT:3306
    volumes:
        - "./shared/mysql/data/db:/var/lib/mysql"
    environment:
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
    restart: always
