admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'

sonata_admin:
    resource: .
    type: sonata_admin

sonata_user_admin:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /resetting