#
# Common
#
name:
  override: ""
  useReleaseName: true

#
# Docker image
#
registry:
  url: <TODO>
  secrets: []

#
# application configuration
#
app:
  image:
    path: "<TODO>"
    version: "<CHANGE_IT>"
    pullPolicy: "Always"
  ports:
    http: 80
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 100Mi

#
# nginx configuration
#
nginx:
  image:
    path: "<TODO>"
    version: "<CHANGE_IT>"
    pullPolicy: "Always"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 100Mi

#
# Probes
#
livenessProbe:
  enabled: true
  initialDelaySeconds: 15
  periodSeconds: 20
  failureThreshold: 5
  successThreshold: 2
  timeoutSeconds: 5
  path: /
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 5
  successThreshold: 2
  timeoutSeconds: 5
  path: /

nodeSelector: { }
topologySpreadConstraints: [ ]
tolerations: []
affinity: { }
