fos_user:
  db_driver:      orm # can be orm or odm
  firewall_name:  main
  user_class:     App\Entity\User
  from_email:
    address:       webmaster@example.com
    sender_name:   webmaster

  group:
    group_class:   App\Entity\Group
    group_manager: sonata.user.orm.group_manager                    # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)

  service:
    user_manager: sonata.user.orm.user_manager                      # If you're using doctrine orm (use sonata.user.mongodb.user_manager for mongodb)
    mailer: fos_user.mailer.twig_swift
