knp_snappy:
    pdf:
        enabled:    true
        binary:     /var/www/symfony/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64
        options:    []
    image:
        enabled:    true
        binary:     /var/www/symfony/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64
        options:    []