liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public/"

    filter_sets:
        cache: ~
        preview:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }