sonata_admin:
    title:      ' '
    title_logo: /render/logo.png
    security:
        handler: sonata.admin.security.handler.role
    breadcrumbs:
        child_admin_route: show
    assets:
        javascripts:
            - bundles/sonatacore/vendor/jquery/dist/jquery.min.js
            - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js
            - bundles/sonatacore/vendor/moment/min/moment.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
            - bundles/sonatacore/vendor/bootstrap/dist/js/bootstrap.min.js
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js
            - bundles/sonataadmin/vendor/jquery-form/jquery.form.js
            - bundles/sonataadmin/jquery/jquery.confirmExit.js
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js
            - bundles/sonatacore/vendor/select2/select2.min.js
            - bundles/sonataadmin/vendor/admin-lte/dist/js/app.min.js
            - bundles/sonataadmin/vendor/iCheck/icheck.min.js
            - bundles/sonataadmin/vendor/waypoints/lib/jquery.waypoints.min.js
            - bundles/sonataadmin/vendor/waypoints/lib/shortcuts/sticky.min.js
            - bundles/sonataadmin/Admin.js
            - bundles/sonataadmin/treeview.js
            - bundles/fosckeditor/ckeditor.js
    templates:
        layout: admin/layout.html.twig
        tab_menu_template: admin/tab_menu_template.html.twig
        select: AppBundle:Admin:CRUD:list__select.html.twig
    dashboard:
        groups:
            app.clients:
                label: Клиенты
                icon: '<i class="fa fa-users"></i>'
                items:
                    - route: my_clients
                      label: 'Мои клиенты'
                      roles:
                        [ROLE_APP_CLIENT_ADMIN_LIST, ROLE_ADMIN]
                    - route: add_client
                      label: 'Добавить клиента'
                      roles:
                        [ROLE_APP_CLIENT_ADMIN_CREATE, ROLE_ADMIN]
                    - route: my_ex_clients
                      label: 'Мои бывшие клиенты'
                      roles:
                        [ROLE_APP_CLIENT_ADMIN_LIST, ROLE_ADMIN]
            app.profile:
                label: Личный кабинет
                icon: '<i class="fa fa-user"></i>'
                items:
                    - route: my_services
                      label: 'Оказанные мной услуги'
                      roles:
                        [ROLE_APP_SERVICE_ADMIN_ALL, ROLE_ADMIN]
                    - route: profile
                      label: 'Мой профиль'
                      roles:
                        [ROLE_SONATA_USER_ADMIN_USER_EDIT, ROLE_ADMIN]
            app.settings:
                label: Настройки
                icon: '<i class="fa fa-wrench"></i>'
                items:
                    - app.client_field.admin
                    - app.region.admin
                    - app.service_type.admin
                    - app.contract_item_type.admin
                    - app.generated_document_type.admin
                    - app.generated_document_start_text.admin
                    - app.generated_document_end_text.admin
                    - app.certificate_type.admin
                    - app.menu_item.admin
                    - app.position.admin
                    - sonata.user.admin.user
                    - sonata.user.admin.group
                    - app.client_form.admin
                roles:
                  [ROLE_ADMIN]
