twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'VichUploaderBundle:Form:fields.html.twig'
        - 'form/fields.html.twig'
        - 'SonataFormatterBundle:Form:formatter.html.twig'
        #            - 'SonataMediaBundle:Form:media_widgets.html.twig'
        - 'SonataCoreBundle:Form:datepicker.html.twig'
        - 'VichUploaderBundle:Form:fields.html.twig'
#    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
    globals:
        org_name_short: "%env(ORG_NAME_SHORT)%"
        org_name: "%env(ORG_NAME)%"
        org_description: "%env(ORG_DESCRIPTION)%"
        org_description_short: "%env(ORG_DESCRIPTION_SHORT)%"
        org_contacts_full: "%env(ORG_CONTACTS_FULL)%"
        org_city: "%env(ORG_CITY)%"
        dispensary_name: "%env(DISPENSARY_NAME)%"
        dispensary_address: "%env(DISPENSARY_ADDRESS)%"
        dispensary_phone: "%env(DISPENSARY_PHONE)%"
        employment_name: "%env(EMPLOYMENT_NAME)%"
        employment_address: "%env(EMPLOYMENT_ADDRESS)%"
        employment_inspection: "%env(EMPLOYMENT_INSPECTION)%"
        sanitation_name: "%env(SANITATION_NAME)%"
        sanitation_address: "%env(SANITATION_ADDRESS)%"
        sanitation_time: "%env(SANITATION_TIME)%"
